import { readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';

/**
 * The data directory registry: every record is a JSON file in
 * content/directory/, generated by scripts/build-directory/ and committed
 * after human review. A page exists because a reviewed file exists — there is
 * no runtime data source. To add, refresh, or remove records, re-run the
 * pipeline (see scripts/build-directory/README.md); never edit records by
 * hand.
 *
 * This module is server-only: it reads the filesystem at build time. Client
 * components use content/directory/index.json instead (see DirectorySearch).
 */

export type Confidence = 'high' | 'medium' | 'low';
export type DirectoryField = { name: string; type: string; alias?: string };
export type DirectoryLayer = {
  id: number | string;
  name: string;
  title?: string;
  geometry?: string | null;
  fields: DirectoryField[];
  feature_count?: number | null;
};
export type DirectoryPlace = { country: string; state?: string | null; confidence: Confidence };
export type DirectoryService = {
  slug: string;
  service_key: string;
  type: string;
  url: string;
  title: string;
  description: string;
  abstract?: string;
  provider?: string;
  place: DirectoryPlace | null;
  themes: { name: string; confidence: Confidence }[];
  bbox: [number, number, number, number] | null;
  layers: DirectoryLayer[];
  formats: string[];
  crs: string[];
  cors_enabled: boolean | null;
  response_ms: number | null;
  last_verified: string;
  discovery_count: number;
  quality_score: number;
};
export type Hub = { slug: string; label: string; services: DirectoryService[] };

const CONTENT_DIR = path.join(process.cwd(), 'content', 'directory');
const MIN_HUB_MEMBERS = 3;

let cache: DirectoryService[] | null = null;

function load(): DirectoryService[] {
  if (cache) return cache;
  const files = readdirSync(CONTENT_DIR).filter(
    (f) => f.endsWith('.json') && f !== 'index.json' && f !== 'removed.json',
  );
  cache = files
    .map((f) => JSON.parse(readFileSync(path.join(CONTENT_DIR, f), 'utf8')) as DirectoryService)
    .sort((a, b) => a.title.localeCompare(b.title));
  return cache;
}

function kebab(text: string): string {
  return text
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function sentenceCase(slugText: string): string {
  const words = slugText.replace(/-/g, ' ');
  return words.charAt(0).toUpperCase() + words.slice(1);
}

export function getAllServices(): DirectoryService[] {
  return load();
}

export function getService(slug: string): DirectoryService | undefined {
  return load().find((s) => s.slug === slug);
}

/** Country and state hubs from confident place tags; small groups stay unlisted. */
export function placeHubs(): Hub[] {
  const groups = new Map<string, Hub>();
  for (const s of load()) {
    if (!s.place || s.place.confidence === 'low') continue;
    const country = { slug: kebab(s.place.country), label: s.place.country };
    const targets = [country];
    if (s.place.state) {
      targets.push({
        slug: `${kebab(s.place.state)}-${kebab(s.place.country)}`,
        label: `${s.place.state}, ${s.place.country}`,
      });
    }
    for (const t of targets) {
      const hub = groups.get(t.slug) ?? { slug: t.slug, label: t.label, services: [] };
      hub.services.push(s);
      groups.set(t.slug, hub);
    }
  }
  return [...groups.values()]
    .filter((h) => h.services.length >= MIN_HUB_MEMBERS)
    .sort((a, b) => a.label.localeCompare(b.label));
}

export function themeHubs(): Hub[] {
  const groups = new Map<string, Hub>();
  for (const s of load()) {
    for (const t of s.themes) {
      if (t.confidence === 'low') continue;
      const hub = groups.get(t.name) ?? { slug: t.name, label: sentenceCase(t.name), services: [] };
      hub.services.push(s);
      groups.set(t.name, hub);
    }
  }
  return [...groups.values()]
    .filter((h) => h.services.length >= MIN_HUB_MEMBERS)
    .sort((a, b) => a.label.localeCompare(b.label));
}

const RELATED_CAP = 5;

export function relatedTo(s: DirectoryService): {
  provider: DirectoryService[];
  place: DirectoryService[];
  theme: DirectoryService[];
} {
  const others = load().filter((o) => o.slug !== s.slug);
  const provider = s.provider
    ? others.filter((o) => o.provider === s.provider).slice(0, RELATED_CAP)
    : [];
  const place = s.place
    ? others
        .filter((o) => o.place && o.place.country === s.place!.country)
        .slice(0, RELATED_CAP)
    : [];
  const themeNames = new Set(s.themes.map((t) => t.name));
  const theme = themeNames.size
    ? others.filter((o) => o.themes.some((t) => themeNames.has(t.name))).slice(0, RELATED_CAP)
    : [];
  return { provider, place, theme };
}

export function featured(count: number): DirectoryService[] {
  return [...load()]
    .sort((a, b) => b.quality_score - a.quality_score || b.discovery_count - a.discovery_count)
    .slice(0, count);
}
